name: awesome_places
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ionicons: ^0.1.2
  provider: ^6.0.2
  image_picker: ^0.8.5
  path_provider: ^2.0.9
  path: ^1.8.0
  location: ^4.4.0
  http: ^0.13.4
  sqflite: ^2.0.2+1
  google_fonts: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true